server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index login.html;

    # Redirection to login
    location = / {
        try_files /login.html =404;
    }

    location /login.html {
        try_files $uri =404;
    }

    location /css/ {
        try_files $uri =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location /crud/ {
        try_files $uri $uri/ /crud/index.html;
    }

    # Redirects /login -> http://crud:4000/login
    location /login {
        proxy_pass http://crud:4000/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Redirects /api/ -> http://crud:4000/api/
    location /api/ {
        proxy_pass http://crud:4000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Redirige /health -> http://crud:4000/health
    location /health {
        proxy_pass http://crud:4000/health;
    }
}